fix:`deploy.yml`修正

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -41,6 +41,13 @@ jobs:
       - name: Build
         run: npm run build
 
+      - name: Show build output
+        run: |
+          pwd
+          ls -la
+          ls -la .next || echo ".next not found"
+          ls -la public || echo "public not found"
+
       # 8. VPS へアップロード
       - name: Upload project to VPS
         uses: appleboy/scp-action@v0.1.7
@@ -50,8 +57,8 @@ jobs:
           password: ${{ secrets.VPS_PASSWORD }}
           port: 22
           source: |
-            .next/
-            public/
+            .next/**/*
+            public/**/*
             package.json
             package-lock.json
           target: /var/www/mui_test
